name: Firebase Cloud Functions

on: 
  pull_request:
    branches: [ main ]
    paths:
      - 'functions/src/**'
  push:
    branches: [ main ]
    paths:
      - 'functions/src/**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

