/// Flutter icons DatePickerCheckMark
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DatePickerCheckMark
///      fonts:
///       - asset: fonts/DatePickerCheckMark.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class DatePickerCheckMark {
  DatePickerCheckMark._();

  static const _kFontFam = 'DatePickerCheckMark';
  static const String _kFontPkg = null;

  static const IconData calendar_check_o =
      IconData(0xf274, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
