name: Release

on: 
  pull_request:
    branches: [ main ]
    paths:
      - "build/app/outputs/flutter-apk/app-release.apk"
  push:
    branches: [ main ]
    paths:
      - "build/app/outputs/flutter-apk/app-release.apk"
jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "/build/app/outputs/flutter-apk/app-release.apk"
        bodyFile: "release-notes.txt"
        token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        name: Set up the repo files
      - uses: w9jds/firebase-action@master
        name: Set up the firebase CLI tool
        with: 
          args: appdistribution:distribute "build/app/outputs/flutter-apk/app-release.apk" --app 1:113842149906:android:67d8ced2378cce6e6d96cb --token "${{secrets.FIREBASE_TOKEN}}" --release-notes-file "release-notes.txt" --groups "devs"
        env:
          FIREBASE_TOKEN: "${{secrets.FIREBASE_TOKEN}}"