name: Firebase Cloud Functions

on: 
  pull_request:
    branches: [ main ]
    paths:
      - 'functions/src/**'
  push:
    branches: [ main ]
    paths:
      - 'functions/src/**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn install
      name: yarn install
    - run: cd functions
    - uses: icrawl/action-tsc@v1
      name: tsc
      with:
        project: '/functions'