name: Upgrade Version
on:
  release:
  push:
    paths:
      - "pubspec.yaml"
      - "lib/*"


jobs:
  upgrade-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pocket-apps/action-update-version@v1
        with:
          files: 'pubspec.yaml, package.json'
          version-regexp: '\d+.\d+.\d+'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-name: main
          spacing-level: 0
          author-name: CD/CI version updater
          author-email: halvorvivelstad@gmail.com
